GestorCuentasTarjetas.FrontendMvc/Controllers/TarjetaController.cs
using Microsoft.AspNetCore.Mvc;

using GestorCuentasTarjetas.FrontendMvc.Models;
namespace GestorCuentasTarjetas.FrontendMvc.Controllers
{
    public class TarjetaController : Controller
    {
        
        public async Task<IActionResult> Index()
        {
            using (HttpClient client = new HttpClient())
            {
                string apiUrl = "https://localhost:7165/api/Tarjeta/Lista";

                HttpResponseMessage response = await client.GetAsync(apiUrl);

                if (response.IsSuccessStatusCode)
                {
                   
                    var jsonResponse = await response.Content.ReadAsStringAsync();
                   
                    
                    List<Tarjeta> tarjetas = await response.Content.ReadAsAsync<List<Tarjeta>>();

                    return View(tarjetas);
                }
                else
                {
                    // Retorna la vista con una lista vacía
                    return View(new List<Tarjeta>());
                }
            }
        }

        [HttpGet]
        [Route("ObtenerEstadoCuenta/{idTarjeta}")]
        public async Task<IActionResult> ObtenerEstadoCuenta(int idTarjeta)
        {
            try
            {
               
                using (HttpClient client = new HttpClient())
                {
                    string apiUrl = $"https://localhost:7165/api/Tarjeta/ObtenerEstadoCuentaDetallado/{idTarjeta}";

                    HttpResponseMessage response = await client.GetAsync(apiUrl);

                    if (response.IsSuccessStatusCode)
                    {
                        EstadoCuenta estadoCuentaResponse = await response.Content.ReadAsAsync<EstadoCuenta>();
                     

                        var transacciones = estadoCuentaResponse.Transacciones;

                        
                        var totalComprasPorMes = CalcularTotalComprasPorMes(transacciones);

                        ViewBag.TotalComprasPorMes = totalComprasPorMes;

                        return View(estadoCuentaResponse);
                    }
                    else
                    {
                        return View(new EstadoCuenta());
                    }
                }
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Error : {ex.Message}");
            }
        }

        private Dictionary<string, decimal> CalcularTotalComprasPorMes(List<Transaccion> transacciones)
        {
            var totalComprasPorMes = new Dictionary<string, decimal>();

            foreach (var transaccion in transacciones)
            {
                if (transaccion.TipoTransaccion == "Compra")
                {
                    var clave = $"{transaccion.Fecha.Month}/{transaccion.Fecha.Year}";

                    if (totalComprasPorMes.ContainsKey(clave))
                    {
                        totalComprasPorMes[clave] += transaccion.Monto;
                    }
                    else
                    {
                        totalComprasPorMes[clave] = transaccion.Monto;
                    }
                }
            }

            return totalComprasPorMes;
        }

        [HttpGet]
        public async Task<ActionResult> BuscarPorNombre(string nombreTarjeta)
        {
            try
            {
                using (HttpClient client = new HttpClient())
                {
                    string apiUrl = $"https://localhost:7165/api/Tarjeta/BuscarPorNombre/{nombreTarjeta}";

                    HttpResponseMessage response = await client.GetAsync(apiUrl);

                    if (response.IsSuccessStatusCode)
                    {
                        var resultados = await response.Content.ReadAsAsync<List<Tarjeta>>();

                        return View("Index", resultados);
                    }
                    else
                    {
                        return View("Index", new List<Tarjeta>());
                    }
                }
            }
            catch (Exception ex)
            {            
                Console.WriteLine($"Error en la búsqueda: {ex.Message}");
                return View("Index", new List<Tarjeta>());
            }

        }
    }

}

GestorCuentasTarjetas.FrontendMvc/Controllers/TransaccionController.cs
using Microsoft.AspNetCore.Mvc;
using GestorCuentasTarjetas.FrontendMvc.Models;

namespace GestorCuentasTarjetas.FrontendMvc.Controllers
{
    public class TransaccionController : Controller
    {
      
        [HttpGet]
        [Route("ObtenerTranssacion/{idTarjeta}")]
        public async Task<IActionResult> ObtenerTranssacion(int idTarjeta)
        {
            try
            {

                using (HttpClient client = new HttpClient())
                {
                    string apiUrl = $"https://localhost:7165/api/Tarjeta/ObtenerEstadoCuentaDetallado/{idTarjeta}";

                    HttpResponseMessage response = await client.GetAsync(apiUrl);

                    if (response.IsSuccessStatusCode)
                    {
                        EstadoCuenta estadoCuentaResponse = await response.Content.ReadAsAsync<EstadoCuenta>();
                        Tarjeta ptarjeta = new Tarjeta();

                        var PorcentajeInteresConfigurable = 25;

                        var InteresBonificable = ptarjeta.SaldoActual * PorcentajeInteresConfigurable;

                        ViewBag.InteresBonificable = InteresBonificable;


                        var transacciones = estadoCuentaResponse.Transacciones;


                        return View(estadoCuentaResponse);
                    }
                    else
                    {
                        return View(new EstadoCuenta());
                    }
                }
            }
            catch (Exception ex)
            {
              
                return StatusCode(500, $"Error : {ex.Message}");

            }
        }
    }
}

GestorCuentasTarjetas.FrontendMvc/Views/Transaccion/ObtenerTranssacion.cshtml
@using System.Globalization

@model GestorCuentasTarjetas.FrontendMvc.Models.EstadoCuenta

@{
    ViewData["Title"] = "ObtenerTranssacion";
}


<div class="container mt-5">
    <div class="card mb-4">
        <div class="card-header bg-danger text-white">
            <h2 class="text-center">Transacciones</h2>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <dl class="row">
                        <dt class="col-sm-4">Nombre del Cliente:</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Tarjeta.TitularNombre)</dd>
                        <dt class="col-sm-4">Número de Tarjeta:</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Tarjeta.NumeroTarjeta)</dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>

    <div class="card mb-4">
        <div class="card-header bg-danger text-white">
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>Tipo de Transacción</th>
                        <th>Fecha</th>
                        <th>Descripción</th>
                        <th>Monto</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var transaccion in Model.Transacciones)
                    {
                        <tr>
                            <td>@transaccion.TipoTransaccion</td>
                            <td>@transaccion.Fecha.ToString("dd/MM/yyyy")</td>
                            <td>@transaccion.Descripcion</td>
                            <td>@transaccion.Monto.ToString("C", CultureInfo.CreateSpecificCulture("en-US"))</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </div>
    <div class="text-center">
        <a asp-controller="Tarjeta" asp-action="Index" class="btn btn-secondary">Regresar</a>
    </div>