GestorCuentasTarjetas.FrontendMvc/Models/Tarjeta.cs
using System.ComponentModel.DataAnnotations;

namespace GestorCuentasTarjetas.FrontendMvc.Models
{
    public class Tarjeta
    {
        [Key]
        public int IdTarjeta { get; set; }
        public string TitularNombre { get; set; }
        public string NumeroTarjeta { get; set; }
        public decimal SaldoActual { get; set; }
        public decimal LimiteCredito { get; set; }
        public decimal SaldoDisponible { get; set; }
    }

}

GestorCuentasTarjetas.FrontendMvc/Controllers/PagoController.cs
using Microsoft.AspNetCore.Mvc;

using GestorCuentasTarjetas.FrontendMvc.Models;

namespace GestorCuentasTarjetas.FrontendMvc.Controllers
{
    public class PagoController : Controller
    {

        private readonly IHttpClientFactory _httpClientFactory;

        public PagoController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }


        [HttpGet]
        [Route("CrearPago/{idTarjeta}")]
        public IActionResult CrearPago(int idTarjeta)
        {
            return View();
        }



        [HttpPost]
        [Route("CrearPago/{idTarjeta}")]

        public async Task<IActionResult> CrearPago(int idTarjeta, NuevoPago nuevoPago, EstadoCuenta estadoCuenta)
        {
            try
            {
                using (HttpClient client = _httpClientFactory.CreateClient())
                {
                    string apiUrl = "https://localhost:7165/api/Pago/AgregarPago";

                    var datosPago = new
                    {
                        TarjetaCreditoId = idTarjeta,
                        Monto = nuevoPago.Monto,
                    };

                    HttpResponseMessage response = await client.PostAsJsonAsync(apiUrl, datosPago);

                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index", "Tarjeta");
                    }

                    else
                    {
                        return StatusCode((int)response.StatusCode);
                    }
                }
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Error al crear el pago: {ex.Message}");
            }


        }

        

    }
}

GestorCuentasTarjetas.FrontendMvc/Controllers/TarjetaController.cs
using Microsoft.AspNetCore.Mvc;

using GestorCuentasTarjetas.FrontendMvc.Models;
namespace GestorCuentasTarjetas.FrontendMvc.Controllers
{
    public class TarjetaController : Controller
    {
        
        public async Task<IActionResult> Index()
        {
            using (HttpClient client = new HttpClient())
            {
                string apiUrl = "https://localhost:7165/api/Tarjeta/Lista";

                HttpResponseMessage response = await client.GetAsync(apiUrl);

                if (response.IsSuccessStatusCode)
                {
                   
                    var jsonResponse = await response.Content.ReadAsStringAsync();
                   
                    
                    List<Tarjeta> tarjetas = await response.Content.ReadAsAsync<List<Tarjeta>>();

                    return View(tarjetas);
                }
                else
                {
                    // Retorna la vista con una lista vacía
                    return View(new List<Tarjeta>());
                }
            }
        }

        [HttpGet]
        [Route("ObtenerEstadoCuenta/{idTarjeta}")]
        public async Task<IActionResult> ObtenerEstadoCuenta(int idTarjeta)
        {
            try
            {
               
                using (HttpClient client = new HttpClient())
                {
                    string apiUrl = $"https://localhost:7165/api/Tarjeta/ObtenerEstadoCuentaDetallado/{idTarjeta}";

                    HttpResponseMessage response = await client.GetAsync(apiUrl);

                    if (response.IsSuccessStatusCode)
                    {
                        EstadoCuenta estadoCuentaResponse = await response.Content.ReadAsAsync<EstadoCuenta>();
                     

                        var transacciones = estadoCuentaResponse.Transacciones;

                        
                        var totalComprasPorMes = CalcularTotalComprasPorMes(transacciones);

                        ViewBag.TotalComprasPorMes = totalComprasPorMes;

                        return View(estadoCuentaResponse);
                    }
                    else
                    {
                        return View(new EstadoCuenta());
                    }
                }
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Error : {ex.Message}");
            }
        }

        private Dictionary<string, decimal> CalcularTotalComprasPorMes(List<Transaccion> transacciones)
        {
            var totalComprasPorMes = new Dictionary<string, decimal>();

            foreach (var transaccion in transacciones)
            {
                if (transaccion.TipoTransaccion == "Compra")
                {
                    var clave = $"{transaccion.Fecha.Month}/{transaccion.Fecha.Year}";

                    if (totalComprasPorMes.ContainsKey(clave))
                    {
                        totalComprasPorMes[clave] += transaccion.Monto;
                    }
                    else
                    {
                        totalComprasPorMes[clave] = transaccion.Monto;
                    }
                }
            }

            return totalComprasPorMes;
        }

        [HttpGet]
        public async Task<ActionResult> BuscarPorNombre(string nombreTarjeta)
        {
            try
            {
                using (HttpClient client = new HttpClient())
                {
                    string apiUrl = $"https://localhost:7165/api/Tarjeta/BuscarPorNombre/{nombreTarjeta}";

                    HttpResponseMessage response = await client.GetAsync(apiUrl);

                    if (response.IsSuccessStatusCode)
                    {
                        var resultados = await response.Content.ReadAsAsync<List<Tarjeta>>();

                        return View("Index", resultados);
                    }
                    else
                    {
                        return View("Index", new List<Tarjeta>());
                    }
                }
            }
            catch (Exception ex)
            {            
                Console.WriteLine($"Error en la búsqueda: {ex.Message}");
                return View("Index", new List<Tarjeta>());
            }

        }
    }

}

GestorCuentasTarjetas.FrontendMvc/Controllers/TransaccionController.cs
using Microsoft.AspNetCore.Mvc;
using GestorCuentasTarjetas.FrontendMvc.Models;

namespace GestorCuentasTarjetas.FrontendMvc.Controllers
{
    public class TransaccionController : Controller
    {
      
        [HttpGet]
        [Route("ObtenerTranssacion/{idTarjeta}")]
        public async Task<IActionResult> ObtenerTranssacion(int idTarjeta)
        {
            try
            {

                using (HttpClient client = new HttpClient())
                {
                    string apiUrl = $"https://localhost:7165/api/Tarjeta/ObtenerEstadoCuentaDetallado/{idTarjeta}";

                    HttpResponseMessage response = await client.GetAsync(apiUrl);

                    if (response.IsSuccessStatusCode)
                    {
                        EstadoCuenta estadoCuentaResponse = await response.Content.ReadAsAsync<EstadoCuenta>();
                        Tarjeta ptarjeta = new Tarjeta();

                        var PorcentajeInteresConfigurable = 25;

                        var InteresBonificable = ptarjeta.SaldoActual * PorcentajeInteresConfigurable;

                        ViewBag.InteresBonificable = InteresBonificable;


                        var transacciones = estadoCuentaResponse.Transacciones;


                        return View(estadoCuentaResponse);
                    }
                    else
                    {
                        return View(new EstadoCuenta());
                    }
                }
            }
            catch (Exception ex)
            {
              
                return StatusCode(500, $"Error : {ex.Message}");

            }
        }
    }
}

GestorCuentasTarjetas.FrontendMvc/Views/Tarjeta/Index.cshtml
@model IEnumerable<GestorCuentasTarjetas.FrontendMvc.Models.Tarjeta>

@{
    ViewData["Title"] = "Index";
}

<div class="d-flex justify-content-between align-items-center">
    <h2 style="margin: 40px;">Listado de Tarjetas</h2>

    <form class="form-inline" action="@Url.Action("BuscarPorNombre", "Tarjeta")" method="get">
        <div class="input-group mb-3">
            <input type="text" name="nombreTarjeta" style="margin-right: 10px;" id="nombreTarjeta" class="form-control" placeholder="Nombre " />
            <div class="input-group-append">
                <button type="submit" class="btn btn-primary" style="margin-right: 10px;">Buscar</button>
            </div>
        </div>

    </form>
</div>

<div class="d-flex justify-content-center mt-4">
    <table id="customers" class="table table-striped text-center align-middle">
        <thead>
            <tr>
                <th class="borIz">Número de Tarjeta</th>
                <th>Nombre del Cliente</th>
                <th class="borDer">Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.NumeroTarjeta)</td>
                    <td>@Html.DisplayFor(modelItem => item.TitularNombre)</td>
                    <td>
                        <div class="btn-group">
                            <a asp-action="ObtenerEstadoCuenta" asp-route-idTarjeta="@item.IdTarjeta" class="btn btn-primary btn-sm boton-con-espacio">Ver Estado de Cuenta</a>
                            <a asp-controller="Compra" asp-action="CrearCompra" asp-route-idTarjeta="@item.IdTarjeta" class="btn btn-success btn-sm boton-con-espacio">Nueva Compra</a>
                            <a asp-controller="Pago" asp-action="CrearPago"  asp-route-idTarjeta="@item.IdTarjeta" class="btn btn-danger btn-sm boton-con-espacio">Hacer Un Pago</a>
                            <a asp-controller="Transaccion" asp-action="ObtenerTranssacion" asp-route-idTarjeta="@item.IdTarjeta" class="btn btn-secondary btn-sm">Transacciones</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<style>
    .boton-con-espacio {
        margin-right: 10px;
    }
</style>

GestorCuentasTarjetas.FrontendMvc/Views/Tarjeta/ObtenerEstadoCuenta.cshtml
@using System.Globalization
@model GestorCuentasTarjetas.FrontendMvc.Models.EstadoCuenta

@{
    ViewData["Title"] = "ObtenerEstadoCuenta";
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
}

<div class="container mt-5">
    <div class="card mb-4">
        <div class="card-header bg-danger text-white">
            <h3>Estado de Cuenta de TC</h3>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <dl class="row">
                        <dt class="col-sm-4">Nombre del Cliente:</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Tarjeta.TitularNombre)</dd>
                        <dt class="col-sm-4">Número de Tarjeta:</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Tarjeta.NumeroTarjeta)</dd>
                    </dl>
                </div>

                <div class="col-md-6">
                    <dl class="row">
                        <dt class="col-sm-4">Saldo Actual:</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Tarjeta.SaldoActual)</dd>
                        <dt class="col-sm-4">Límite de Crédito:</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Tarjeta.LimiteCredito)</dd>
                        <dt class="col-sm-4">Saldo Disponible:</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Tarjeta.SaldoDisponible)</dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>

    <div class="card mb-4">
        <div class="card-header bg-danger text-white">
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>Tipo de Transacción</th>
                        <th>Fecha</th>
                        <th>Descripción</th>
                        <th>Monto</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var transaccion in Model.Transacciones)
                    {
                        <tr>
                            <td>@transaccion.TipoTransaccion</td>
                            <td>@transaccion.Fecha.ToString("dd/MM/yyyy")</td>
                            <td>@transaccion.Descripcion</td>
                            <td>@transaccion.Monto.ToString("C", CultureInfo.CreateSpecificCulture("en-US"))</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    <div class="card mb-4">
        <div class="card-header bg-danger text-white">
            <h4>Compras por Mes</h4>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>Mes</th>
                        <th>Total de Compras</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var totalCompraPorMes in ViewBag.TotalComprasPorMes)
                    {
                        var mesYAnio = totalCompraPorMes.Key;
                        var montoTotal = totalCompraPorMes.Value;

                        var mesNumero = int.Parse(mesYAnio.Split('/')[0]);
                        var nombreMes = CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(mesNumero);
                        nombreMes = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(nombreMes);

                        <tr>
                            <td>@nombreMes</td>
                            <td>@montoTotal.ToString("C", CultureInfo.CreateSpecificCulture("en-US"))</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    <div class="text-center">
                    <a asp-controller="Tarjeta" asp-action="Index" class="btn btn-secondary">Regresar</a>
    </div>
</div>